name: unit test

on:
  pull_request:
    branches:
    - main
    - release/**

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Check docs up to date
        run: |
          set -euo pipefail
          go run cmd/docs/main.go
          if [[ `git status --porcelain` ]]; then
            echo "Docs are not up-to-date"
            exit 1
          fi

      - name: Test
        run: go test -v ./pkg/...

      - name: Report coverage
        uses: codecov/codecov-action@v5.0.7
